### ISSUE TITLE
Access to other components from the request handler

### ISSUE THREAD

**Issue by podviaznikov** [weavejester/ring-jetty-component#1]
Is there any way how can I access other components in my request handler?

E.x. how to get access to database component in the context of http request.

**Comment by weavejester** [comment]
That's beyond the scope of this component, as the idea is that the `:app` component will deal with the handler. However, take a look at the [Duct](https://github.com/weavejester/duct) template. That demonstrates one possible way of hooking a handler, database, and adapter component together.
